[project]
name = "perovstats"
version = "0.1.0"

[project.scripts]
perovstats = "perovstats.cli:main"

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
target-version = "py311"
